### ISSUE TITLE
Palyground is not working correctly in Safari 7.1.3 (9537.85.12.18)

### ISSUE THREAD

**Issue by linc01n** [mizchi/md2react#5]
The result content is not in the preview box. It shows under the Fork me link.

![screen shot 2015-03-09 at 9 53 15 am](https://cloud.githubusercontent.com/assets/667272/6548886/1e716792-c642-11e4-9e92-3c3b40a95167.png)

**Comment by mizchi** [comment]
Oh, Safari need vendor prefix to use display:flex, I will fix later
